kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: portal-read
  labels:
    app: portal-rbac
rules:
  - apiGroups: [""]
    resources: ["services","secrets"]
    verbs: ["get", "list","watch"]
  - apiGroups: ["networking.istio.io"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "list", "watch", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list","watch"]
  - apiGroups: ["extensions","networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list","watch"]

